chatbot/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^$',views.home),
    url(r'^options/',views.options),
    url(r'^start_conv/', include('conversation.urls')),
    url(r'^upload/', include('upload_dataset.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^personalize/', include('personalization.urls')),
]

urlpatterns += staticfiles_urlpatterns()

personalization/urls.py
from django.contrib import admin
from . import views
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name='personalization'

urlpatterns = [
    url(r'^$',views.personalize, name="personalize"),
]


urlpatterns += staticfiles_urlpatterns()

personalization/models.py
from django.db import models

# Create your models here.

personalization/views.py
from django.shortcuts import render

import firebase_admin
from firebase_admin import credentials
from google.cloud.firestore_v1 import ArrayRemove, ArrayUnion

cred = credentials.Certificate(("Key.json"))


from firebase_admin import firestore
db = firestore.client()
records = db.collection(u'recs')
docs = records.stream()


def personalize(request):
    if(request.method=="POST"):
        question = request.POST.get('question')
        answer = request.POST.get('answer')

        doc=records.document(request.session['emailid'])

        user_conv_old = doc.get().to_dict()['userConv']
        bot_conv_old = doc.get().to_dict()['botConv']



        user_conv_old.append(question)
        bot_conv_old.append(answer)

        print(user_conv_old)
        print(bot_conv_old)

        doc.update({
            u'userConv' : user_conv_old,
            u'botConv' : bot_conv_old
        })

        print(question, answer)
        return render(request, 'personalize.html',{"success":question})
    else:
        return render(request , 'personalize.html')

personalization/templates/personalize.html
{% extends "collapse.html" %}

{% block inner %}


  <div class='form-group m-4'>

    <div class="text-center">
      <h2>Make your chatbot more personalized by adding you own questions and responses </h2>
      <p>These can serve as reminders for you!</p>
    </div>
    <form class="" action="{% url 'personalization:personalize' %}" method="post">


      {% csrf_token %}

      <label for="emailid">Question</label>
      <input type="text" name="question" class="form-control" value=""></input></br>

      <label for="password">Expected answer</label>
      <input type="text" name="answer" class="form-control" value=""></input></br>

      <button type="submit" class="btn btn-primary">Add to my records</button>

    </form>

    {% if exception %}
      <p> {{ exception }}</p>
    {% endif %}

    {% if success %}
    <div class='text-center'></br></br></br></br>
      <p> Your response has been saved in your record successfully! </p>
      <button type='button' class="btn btn-primary text-center"><a href="/start_conv/" class='text-white'>Proceed</a></button>
    </div>
    {% endif %}


  </div>


{% endblock %}