accounts/urls.py
from django.contrib import admin
from . import views
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name='accounts'

urlpatterns = [
    url(r'^$',views.choices, name="index"),
    url(r'^signup/$',views.signup_view, name='signup'),
    url(r'^login/$',views.login_view, name='login'),

]


urlpatterns += staticfiles_urlpatterns()

chatbot/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^$',views.home),
    url(r'^options/',views.options),
    url(r'^start_conv/', include('conversation.urls')),
    url(r'^upload/', include('upload_dataset.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^personalize/', include('personalization.urls')),
]

urlpatterns += staticfiles_urlpatterns()

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect

import pyrebase


firebase = pyrebase.initialize_app(config)

auth = firebase.auth()

import firebase_admin
from firebase_admin import credentials

cred = credentials.Certificate("Key.json")

from firebase_admin import firestore
db = firestore.client()


def choices(request):
    return render(request, 'choices.html')


def login_view(request):
    if(request.method=="GET"):

            return render(request, 'login.html')

    else:

        emailid = request.POST.get('emailid').lower()
        password = request.POST.get('password')



        try:

            user = auth.sign_in_with_email_and_password(emailid, password)

            if(auth.get_account_info(user['idToken'])['users'][0]['emailVerified']==True):

                request.session['emailid'] = emailid
                print("done")

                return render(request, 'login.html',{ "success" : True  })
            else:
                return render(request, 'login.html',{ "exception" : "Please verify your email-id first if you haven't already."  })

        except:
            return render(request, 'login.html',{ "exception" : "Sorry! Make sure you have entered your email id and password correctly. If that's right make sure you have already created an account."  })



def signup_view(request):
    if(request.method=="GET"):
        return render(request, 'signup.html')

    else:

        username = request.POST.get('name')
        emailid = request.POST.get('emailid').lower()
        password = request.POST.get('password')

        user={}

        try:
            user = auth.create_user_with_email_and_password(emailid, password)
            auth.send_email_verification(user['idToken'])
        except:
            return render(request, 'signup.html', {"exception":"This email id has been taken by someone already or does not exist. Also make sure that your password has at least 6 characters."})

        doc_ref = db.collection(u'users').document(user['email'])
        doc_ref.set({
            'Uppermost':[]
        })


        doc_ref2 = db.collection(u'records').document(user['email'])
        doc_ref2.set({
            'userConv':[],
            'botConv':[]
        })

        return render(request, 'signup.html', {"success": "Hey!" + username + "! An email has been sent to your email id. Please verify it's you and then hit sign in on."})

accounts/templates/choices.html
{% extends "base_layout.html" %}

{% block content %}



    <div class="m-5">
      <form class="logout-link" action="/" method="post">
        <div class="form-group m-10">

          <a href="{% url 'accounts:signup' %}" class='text-white'><button type="button" class="btn btn-primary btn-lg btn-block m-1">Sign up</button></a>
          <a href="{% url 'accounts:login' %}" class='text-white'><button type="button" class="btn btn-primary btn-lg btn-block m-1">Log in</button></a>




        </div>
      </form>
    </div>

{% endblock %}

accounts/templates/login.html
{% extends "base_layout.html" %}

{% block content %}


  <div class='form-group m-4'>

    <h1>Log in if you have an account already </h1>
    <form class="" action="{% url 'accounts:login' %}" method="post">


      {% csrf_token %}

      <label for="emailid">E-mail Id</label>
      <input type="text" name="emailid" class="form-control" value=""></input></br>

      <label for="password">Password</label>
      <input type="password" name="password" class="form-control" value=""></input></br>

      <button type="submit" class="btn btn-primary">Log in</button>

    </form>

    {% if exception %}
      <p> {{ exception }}</p>
    {% endif %}

    {% if success %}
    <div class='text-center'></br></br></br></br>
      <p>Log in successful! Hit proceed to speak to the chatbot! </p>
      <!-- <button type='button' class="btn btn-primary text-center"><a href="/start_conv/" class='text-white'>Proceed</a></button> -->
      <a href="/options/" class='text-white'><button type='button' class="btn btn-primary text-center">Proceed</button></a>

    </div>
    {% endif %}


  </div>


{% endblock %}

accounts/templates/signup.html
{% extends "base_layout.html" %}

{% block content %}


  <div class='form-group m-4'>

    <h1>Sign up if you are a new user </h1>
    <form class="" action="{% url 'accounts:signup' %}" method="post">


      {% csrf_token %}

      <label for="name">Name</label>
      <input type="text" name="name" class="form-control" value=""></input></br>

      <label for="emailid">E-mail Id</label>
      <input type="text" name="emailid" class="form-control" value=""></input>
      <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small></br>

      <label for="password">Password</label>
      <input type="password" name="password" class="form-control" value=""></input></br>

      <button type="submit" class="btn btn-primary">Sign up</button>

    </form>

    {% if exception %}
      <p> {{ exception }}</p>
    {% endif %}

    {% if success %}
      <p> {{ success }} <a href="/accounts/login/"> login page</a></p>
    {% endif %}


  </div>


{% endblock %}